version: "3.9"

services:
  web-color-1:
    container_name: color1-build
    image: dev-flask-color
    build:
      context: .
      labels:
        maintainer: "Robert Silva"
      tags:
        - "robertsilvatech/flask-color:1.0.0"
        - "app-oficinadocker"
    ports:
      - "5000:5000"
    environment:
      - COLOR=GREEN
    networks:
      - compose-lab

networks:
  compose-lab:
    driver: bridge

